/**
 * THIS FILE IS GENERATED by `gulp env` command from `env.json`
 * Generated on Thu Apr 27 2017 04:16:29 GMT-0500 (Central Daylight Time)
 *
 * Make sure the keys in `env.model.ts` exist in `env.json`
 * otherwise it'll throw message like this
 * Property '<missing-key>' is missing in type '{}'
 *
 * Feel free to modify for direct updates in development
 */
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ENV = {};
//# sourceMappingURL=env.js.map